// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBim11nuu_qXJZgBgUcVZ0bToDfdKitBlw',
    appId: '1:917374234234:web:f96d58b3086d1d0c3715c3',
    messagingSenderId: '917374234234',
    projectId: 'flutter-ruru-mycat',
    authDomain: 'flutter-ruru-mycat.firebaseapp.com',
    storageBucket: 'flutter-ruru-mycat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGXQJuu8cb8Edp8nj0czEnS7Zvd3LYaps',
    appId: '1:917374234234:android:432f60ed5adb907e3715c3',
    messagingSenderId: '917374234234',
    projectId: 'flutter-ruru-mycat',
    storageBucket: 'flutter-ruru-mycat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwv_EAeXtLLQWlLDRBNNmhaREBkiCknVk',
    appId: '1:917374234234:ios:0cfc32dffb29d3433715c3',
    messagingSenderId: '917374234234',
    projectId: 'flutter-ruru-mycat',
    storageBucket: 'flutter-ruru-mycat.appspot.com',
    iosClientId: '917374234234-mmn52tqghd9tp5g33ar62gu8nrrdqsq7.apps.googleusercontent.com',
    iosBundleId: 'com.ruru.mycat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwv_EAeXtLLQWlLDRBNNmhaREBkiCknVk',
    appId: '1:917374234234:ios:3b0305519e92170f3715c3',
    messagingSenderId: '917374234234',
    projectId: 'flutter-ruru-mycat',
    storageBucket: 'flutter-ruru-mycat.appspot.com',
    iosClientId: '917374234234-ferq57ermrko365575qspjhod79kl3ag.apps.googleusercontent.com',
    iosBundleId: 'com.ruru.mycat.RunnerTests',
  );
}
